### PR TITLE
Port core and math code to C#

### LINKED ISSUE #678: IntelliSense for cs files of SHVDN
When editing cs files of SHVDN, IntelliSense doesn't work well (at least in VS 2017 and 2015), and this annoys me. Any solutions?

### LINKED ISSUE #690: Port entire C++/CLI code except loader to C#
I've started thinking we can port entire C++/CLI code to C# (except for the loader, of course).
I'm not going to say that I don't like C++/CLI or that I don't want to write C++/CLI code, but it's true that C++/CLI quite poorly supported .NET features.
In fact, I tried to define `ModelInfoClassType` as an internal enum in C++/CLI, but I couldn't and it made me very very sad. 
The major problem to port would be function pointers in the NativeAccess class (raw pointers don't matter, and [I use some of them in C#](https://github.com/kagikn/GlowingPickups/blob/master/GlowingPickups/MemoryAccess.cs#L161)), but we can use funtion pointers via `GetDelegateForFunctionPointer` in C# (and some SHVDN or RPH mods use it).
Besides, I seriously want complete IntelliSense, not incomplete one, and Resharper doesn't support C++/CLI, I'm not using due to lack of money to buy, though. (and I heard MulleDK19 is redoing RPH 2 in C#).

# Porting Status (see [this branch](https://github.com/kagikn/scripthookvdotnet/tree/port-code-to-C%23) for details)
## core
- [X] Console.cs
- [X] Main.cs
- [X] Native.cs (Note: SHV functions haven't been replaced with the methods in wrapper)
- [x] NativeMemory.cs
- [X] Script.cs
- [X] ScriptDomain.cs
- [X] Settings.cs
- [X] P/Invoke methods for SHV functions ~~Wrapper class for SHV functions~~
## scripting
- [X] Matrix.cs
- [X] Quaternion.cs
- [X] Vector2.cs
- [X] Vector3.cs

## ScriptHookVDotNet.csproj
- [x] Fixing some stuff to pass compiler checks
- [x] Testing the stuff in core files directly accessing memory

### PR DESCRIPTION
**Pull request by kagikn**
Close #690, close #678
Don't be surprised at the number of the commits, many simple commits are better than one big and complicated commit in Git.

### CODE REVIEW

File: source/core/ScriptDomain.cs [hunk 1]
```diff
@@ -0,0 +1,908 @@
...
+			setup.ShadowCopyDirectories = path;
+
+			var appdomain = System.AppDomain.CreateDomain("ScriptDomain_" + (path.GetHashCode() * Environment.TickCount).ToString("X"), null, setup, new System.Security.PermissionSet(System.Security.Permissions.PermissionState.Unrestricted));
+			appdomain.InitializeLifetimeService();
+
+			ScriptDomain scriptdomain = null;
+
+			try
+			{
+				scriptdomain = (ScriptDomain)(appdomain.CreateInstanceFromAndUnwrap(typeof(ScriptDomain).Assembly.Location, typeof(ScriptDomain).FullName));
```
Comment (kagikn) [inline source/core/ScriptDomain.cs]: There is something wrong with this line. Any solutions? I need to solve this problem before testing any further .

**Comment by kagikn** [comment]
There must be something wrong with calling wrapper, function pointer offsets, calling function pointer. I need to find out the problem comes from.

File: source/core/Native.cs [hunk 2]
```diff
@@ -0,0 +1,711 @@
...
+                unsafe
+                {
+                    return (T)(Function.ObjectFromNative(typeof(T), (ulong*)(_storage.ToPointer())));
+                }
+            }
+        }
+
+        public sealed class Function
+        {
+            internal unsafe struct NativeTask : IScriptTask
```
Comment (crosire) [inline source/core/Native.cs]: This should be a `class`. Both C++/Cli `ref struct` and `ref class` equal `class` in C#, `value struct` and `value class` equal struct in C#.

File: source/core/Native.cs [hunk 3]
```diff
@@ -0,0 +1,711 @@
...
+            {
+                internal ulong _hash;
+                internal ulong* _result;
+                internal InputArgument[] _arguments;
+
+                public void Run()
+                {
+					Wrapper.NativeInit(_hash);
```
Comment (crosire) [inline source/core/Native.cs]: Why use a separate wrapper library? Wouldn't it be much simpler to simply use P/Invoke?
```c#
[DllImport("ScriptHookV.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "nativeInit")]
static extern void NativeInit(ulong hash);
[DllImport("ScriptHookV.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "nativePush64")]
static extern void NativePush64(ulong val);
[DllImport("ScriptHookV.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "nativeCall")]
static extern ulong* NativeCall();
```
If that doesn't work (since ScriptHookV.dll uses mangled C++ exports and not C exports), we can use the ordinal index instead of the function name to look the exports up:
```c#
[DllImport("ScriptHookV.dll", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "#9")]
static extern void NativeInit(ulong hash); // ?nativeInit@@YAX_K@Z
[DllImport("ScriptHookV.dll", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "#10")]
static extern void NativePush64(ulong val); // ?nativePush64@@YAX_K@Z
[DllImport("ScriptHookV.dll", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "#8")]
static extern ulong* NativeCall(); // ?nativeCall@@YAPEA_KXZ
```

File: source/core/Native.cs [hunk 4]
```diff
@@ -0,0 +1,711 @@
...
+
+                    foreach (var argument in _arguments)
```
Comment (crosire) [inline source/core/Native.cs]: Space vs Tabs 😄 . Note that the "Productivity Power Tools" extension for Visual Studio (which every developer should have installed) asks to fix mixed spaces/tabs when you open a file, so it's really easy to get those sorted out.

File: source/core/Native.cs [hunk 5]
```diff
@@ -0,0 +1,711 @@
...
+            internal static unsafe object ObjectFromNative(Type type, ulong* value)
+            {
+                if (type.IsEnum)
+                {
+                    type = Enum.GetUnderlyingType(type);
+                }
+
+                if (type == typeof(bool))
+                {
+                    unsafe
```
Comment (crosire) [inline source/core/Native.cs]: No need for additional `unsafe` scopes if the whole method is `unsafe` already, right?

File: source/core/Native.cs [hunk 6]
```diff
@@ -0,0 +1,711 @@
...
+                    byte[] buffer = new byte[len];
+                    Marshal.Copy(nativeUtf8, buffer, 0, buffer.Length);
+                    return System.Text.Encoding.UTF8.GetString(buffer);
+                }
+            }
+        }
+        #endregion
+
+        #region Global Variables
+        public struct GlobalVariable
```
Comment (crosire) [inline source/core/Native.cs]: We should consider making most methods of this call `unsafe`, since using it wrongly can cause unsafe code to run followed by memory access exceptions.

File: source/core/ScriptHookWrapper.hpp [hunk 7]
```diff
@@ -0,0 +1,35 @@
...
+*
+*   1. The origin of this software must not be misrepresented; you must not claim that you  wrote the
+*      original  software. If you use this  software  in a product, an  acknowledgment in the product
+*      documentation would be appreciated but is not required.
+*   2. Altered source versions must  be plainly  marked as such, and  must not be  misrepresented  as
+*      being the original software.
+*   3. This notice may not be removed or altered from any source distribution.
+*/
+
+namespace ScriptHookWrapper
```
Comment (crosire) [inline source/core/ScriptHookWrapper.hpp]: I don't think this is needed, see above comment on P/Invoke.

File: Properties/AssemblyInfo.cs [hunk 8]
```diff
@@ -0,0 +1,36 @@
...
+//
+//      Major Version
+//      Minor Version
+//      Build Number
+//      Revision
+//
+// You can specify all the values or you can default the Build and Revision Numbers
+// by using the '*' as shown below:
+// [assembly: AssemblyVersion("1.0.*")]
+[assembly: AssemblyVersion("3.0.0")]
```
Comment (crosire) [inline Properties/AssemblyInfo.cs]: This will break automatic versioning via a preprocessor define. Fortunately it looks like there are ways to work around that with a custom MSBuild task: http://www.andrewconnell.com/blog/Using-MSBuild-to-generate-assembly-version-info-at-build-time-including-SubVersion-fix.

File: ScriptHookVDotNet.csproj [hunk 9]
```diff
@@ -0,0 +1,150 @@
...
+  <ItemGroup>
+    <Folder Include="source\scripting\Game\" />
+    <Folder Include="source\scripting\NaturalMotion\" />
+    <Folder Include="source\scripting\UI\" />
+    <Folder Include="source\scripting\World\Entities\Peds\" />
+    <Folder Include="source\scripting\World\Entities\Vehicles\" />
+    <Folder Include="source\scripting\World\Weapons\" />
+  </ItemGroup>
+  <ItemGroup>
+    <WCFMetadata Include="Connected Services\" />
```
Comment (crosire) [inline ScriptHookVDotNet.csproj]: We don't need that.

File: ScriptHookVDotNet.sln [hunk 10]
```diff
@@ -2,38 +2,105 @@
...
 	ProjectSection(ProjectDependencies) = postProject
-		{019193A7-50C0-444A-84CA-777595E702CD} = {019193A7-50C0-444A-84CA-777595E702CD}
+		{5D98F169-2298-4ECD-977E-24619104AF5D} = {5D98F169-2298-4ECD-977E-24619104AF5D}
 	EndProjectSection
 EndProject
+Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "ScriptHookVWrapperDotNet", "ScriptHookVWrapperDotNet.vcxproj", "{5D98F169-2298-4ECD-977E-24619104AF5D}"
+EndProject
 Global
 	GlobalSection(SolutionConfigurationPlatforms) = preSolution
+		Debug|Any CPU = Debug|Any CPU
```
Comment (crosire) [inline ScriptHookVDotNet.sln]: Should get rid of all the `Any CPU` targets and switch the `ScriptHookVDotNet` C# project to compile for `x64`.

File: ScriptHookVDotNet.sln [hunk 11]
```diff
@@ -2,38 +2,105 @@
...
+		Debug|x64 = Debug|x64
+		NativeGen|Any CPU = NativeGen|Any CPU
```
Comment (crosire) [inline ScriptHookVDotNet.sln]: On that note: The `NativeGen` target is no longer implemented. That should be fixed. I'm not sure how well it works in a csproj MSBuild file, but we could always move it to the "Loader" project if it doesn't.

File: source/scripting/World.cs [hunk 12]
```diff
@@ -687,7 +687,7 @@ public static Ped GetClosestPed(Vector3 position, float radius, params Model[] m
 		/// <summary>
 		/// A fast way to get the total number of vehicles spawned in the world.
 		/// </summary>
-		public static int VehicleCount { get { return MemoryAccess.GetNumberOfVehicles(); } }
+		public static uint VehicleCount => MemoryAccess.GetNumberOfVehicles();
```
Comment (crosire) [inline source/scripting/World.cs]: Sure you want this to be an `uint`? I would generally agree, but since C# is really bitchy about implcitily casting between `int` and `uint` and most iterators in C# use `int` I'm not sure it's the best choice here.

Comment (kagikn) [reply source/scripting/World.cs]: I considered this return value type and concluded entity count in GTA world is unlikely to be above `Int32.MaxValue` (and certainly unlikely to be above 20000). Will revert it.

File: source/core/Native.cs (hunk 2 above)
Comment (kagikn) [reply source/core/Native.cs]: I didn't define this as a `class` for some reason. I know what you're saying, yes.

**Comment by kagikn** [comment]
I fixed the things that can be solved without hesitation.

File: source/core/Native.cs (hunk 3 above)
Comment (kagikn) [reply source/core/Native.cs]: Your concern was right, I confirmed the former P/Invoke lines crash GTA.

File: source/core/Native.cs (hunk 6 above)
Comment (kagikn) [reply source/core/Native.cs]: That idea sounds nice, but I believe we shouldn't make `MemoryAddress` unsafe at least, it means VB.NET scripts can't do the all operations by themselves that C# script can.

File: source/core/Native.cs (hunk 4 above)
Comment (kagikn) [reply source/core/Native.cs]: I didn't know "Productivity Power Tools" had that feature, thanks man.

Comment (kagikn) [reply source/core/Native.cs]: I didn't know "Productivity Power Tools" had that feature, thanks man.

File: Properties/AssemblyInfo.cs (hunk 8 above)
Comment (kagikn) [reply Properties/AssemblyInfo.cs]: It'll take quite long time for me to read. Will change this line after testing memory stuff good enough.

**Comment by kagikn** [comment]
Still even this call in a external script crashes GTA (this call uses Function.Call though). Any solutions?
`var player = Game.Player`

File: Properties/AssemblyInfo.cs (hunk 8 above)
Comment (crosire) [reply Properties/AssemblyInfo.cs]: You don't have to do this. I just noted this here for later. The automated build version wasn't in the V3 branch yet anyway.

**Comment by kagikn** [comment]
Console isn't working properly and external scripts crash the game, for now. I need to fix them.

**Comment by kagikn** [comment]
I'm trying to find out why `ScriptDomain.PinString` is crashing GTA.

**Comment by kagikn** [comment]
I'm trying to find out why ScriptDomain.PinString is crashing the game.

**Comment by kagikn** [comment]
I'm trying to find out why `ScriptDomain.PinString` is crashing the game.

**Comment by kagikn** [comment]
Now `MemoryAccess` constructor has no problems, it doesn't crash the game at least.

**Comment by kagikn** [comment]
I haven't tested memory stuff yet because Script.cs had problem with invoking events. I need to do.

**Comment by kagikn** [comment]
I fixed almost all stuff, and no significant FPS drop compared to C++/CLI version, but I need to fix `EuphoriaMessageTask` (C++/CLI version works now, so...)

**Comment by kagikn** [comment]
`CheckpointBaseAddr` doesn't seem to work, but it's not my fault.

**Comment by kagikn** [comment]
Alright, `EuphoriaMessageTask` is now available in C# and I tested good enough.
@crosire Please verify if this PR is good enough to merge.

**Comment by crosire** [comment]
Looks good. Did a quick test and things seem to be working.
